group_name: "manipulator"
base_frame: "world"
tool_frame: "flange"
poi_names: ["a_forearm","b_mount_flange","b_forearm","flange"]

max_step_size: 0.001
max_cart_acc: 2.5
Tr: 0.15
min_distance: 0.2
v_h: 1.6

n_objects: 1
# min_range: [-0.5,-0.5,0]
# max_range: [ 0.5, 0.5,0.5]
min_range: [-3,-3,0]
max_range: [ 3, 3,3]

n_samples: 1000
only_one_conf_per_conn: false
